FROM ubuntu:14.04.2

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y

### Install Ryu controller
RUN apt-get install -y python-dev python-pip python-lxml python-paramiko
RUN apt-get install -y libxml2-dev
RUN apt-get install -y git
RUN pip install --upgrade six
WORKDIR /root
RUN git clone https://github.com/ttsubo/ryu.git
WORKDIR /root/ryu
RUN git checkout bgpSimulator
WORKDIR /root/ryu/tools
RUN pip install -r pip-requires
WORKDIR /root/ryu
RUN python ./setup.py install
