FROM ubuntu:14.04.1

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y

### Install Ryu controller
RUN apt-get install -y python-dev python-pip python-lxml
RUN apt-get install -y libxml2-dev
RUN apt-get install -y git
RUN pip install --upgrade six
WORKDIR /root
RUN git clone https://github.com/osrg/ryu.git
WORKDIR /root/ryu/tools
RUN pip install -r pip-requires
WORKDIR /root/ryu
RUN python ./setup.py install

### Install Test_automation
WORKDIR /root
RUN git clone https://github.com/ttsubo2000/Test_automation.git
